-- CODE FROM AH4331-13, THIS SHOULD BE A STRAIGHT RE-RUN
-- ALL TABLES IN DMODCUNN SCHEMA UNLESS OTHERWISE NOTED


/*
For matching records, please return the following data elements from the most recent rating:
    Veteran’s SSN
    Veteran’s claim number
    Rating date
    Diagnostic code (8045) or hyphenated diagnostic code
    Text description of rated condition
    SC / NSC
    Percentage of evaluation
    Effective date of evaluation

  requirements clarification:  look at the codesheet data of the last
   rating decision (regardless of date) and provide all percentage/effective
   dates for TBI conditions.  We will not limit the data pull to ratings
   completed after the exam date or where the TBI condition was at issue


*/

-- CHECK LOADED INPUT FILE
SELECT * FROM TBI_4331;

SELECT COUNT(*), COUNT(DISTINCT VA_CLAIM_NUM) FROM TBI_4331;
-- 603    601

SELECT * FROM TBI_4331 WHERE VA_CLAIM_NUM IS NULL;  -- NO RECORDS



SELECT * FROM TBI_4331 WHERE VA_CLAIM_NUM IN
(SELECT VA_CLAIM_NUM FROM
(SELECT VA_CLAIM_NUM, COUNT(*) RECS
FROM   TBI_4331
GROUP BY VA_CLAIM_NUM)
WHERE RECS > 1)
ORDER BY VA_CLAIM_NUM;
-- 2 RECORDS FOR 2 VETERANS (TOTAL OF 4 LINES) WITH DIFFERENT EXAM DATES
-- WILL KEEP ALL AND NOTE IN RESULTS DOCUMENT

 

-- FIRST TABLE WITH LATEST PROMULGATED RATINGS FOR INPUT FILE 
CREATE TABLE AH4331_RERUN_1 AS
SELECT Y.* FROM
(SELECT X.*, 
 ROW_NUMBER() OVER (PARTITION BY X.RID ORDER BY X.RATING_DATE DESC) AS ROW_RANK
 FROM
(SELECT DISTINCT T.*, D.PTCPNT_VET_ID, D.JRN_LCTN_ID RBA_RO,
        D.PRFIL_DT D_PRFIL_DT, TRUNC(D.RATING_DT) RATING_DATE, 
        T.VA_CLAIM_NUM||T.EXAM_DATE AS RID
 FROM   RBA_SS.SS_RBA_PRFIL D, TBI_4331 T, COMMON_SS.SS_PERSON P       
 WHERE  T.VA_CLAIM_NUM = P.FILE_NBR
 AND    P.PTCPNT_ID = D.PTCPNT_VET_ID 
 AND    NVL(D.LOCKED_IND,'X') != 'Y'
 AND    NVL(D.SYSTEM_TYPE_CD,'X') != 'B'
 AND    D.PRMLGN_DT IS NOT NULL) X) Y
WHERE  Y.ROW_RANK = 1;
COMMIT;
 
SELECT COUNT(*) FROM AH4331_RERUN_1; -- 546


SELECT * FROM AH4331_RERUN_1;



-- ADD GRANT/DENIAL DECISION DATA PART 1
CREATE TABLE AH4331_RERUN_2 AS
SELECT DISTINCT D.*, B.BEGIN_DT, B.CNVRTD_BEGIN_DT, B.DSBLTY_ID, B.DSBLTY_DT,
       B.RATING_DECN_ID, B.PRFIL_DT B_PRFIL_DT 
FROM   AH4331_RERUN_1 D, 
       RBA_SS.SS_RATING_DECN B
WHERE  B.PTCPNT_VET_ID = D.PTCPNT_VET_ID
-- new requirement - all effective dates and percentages
-- AND    NVL((TRUNC(B.BEGIN_DT)),'01-JAN-1900') < D.RATING_DATE
-- DO NOT WANT NOT FUTURE EVALS, BUT DO WANT NSC WITH NULL BEGIN_DT
AND    TRUNC(B.PRFIL_DT) = TRUNC(D.D_PRFIL_DT)
-- AND    (B.INACTV_DT IS NULL OR TRUNC(B.INACTV_DT) > TRUNC(D.D_PRFIL_DT);
-- eliminates earlier decisions, inactive date entered at time of decision
-- earlier inactive date means earlier decision, null date means current
-- decision, and later date means a later decision
;
COMMIT;
                                                                                                                                                                          

SELECT *   FROM AH4331_RERUN_2;


-- ADD GRANT/DENIAL DECISION DATA PART 2
CREATE TABLE AH4331_RERUN_3 AS
SELECT DISTINCT B.*, C.DSBLTY_DECN_TYPE_CD, C.DSBLTY_DECN_BASIS_TYPE_CD
FROM   AH4331_RERUN_2 B, 
       RBA_SS.SS_DSBLTY C
WHERE  B.PTCPNT_VET_ID = C.PTCPNT_VET_ID
AND    B.B_PRFIL_DT = C.PRFIL_DT
AND    B.DSBLTY_ID = C.DSBLTY_ID
AND    B.DSBLTY_DT = C.DSBLTY_DT
AND    C.DSBLTY_DECN_TYPE_CD IN ('SVCCONNCTED','NOTSVCCON');
COMMIT;

SELECT *   FROM AH4331_RERUN_3; 
 
 
-- ADD DIAG CODE DATA
-- MULTIPLE EVALUATIONS WITH MULTIPLE BEGIN_DT 
-- PROVIDE ALL EFFECTIVE DATES/EVALUATIONS
CREATE TABLE AH4331_RERUN_4 AS
SELECT DISTINCT B.*, A.HYPNTD_DGNSTC_TYPE_CD, A.DGNSTC_TYPE_CD, A.DGNSTC_TXT,
        A.PRCNT_NBR  
 FROM   AH4331_RERUN_3 B, 
        RBA_SS.SS_DSBLTY_EVALTN A
 WHERE  A.RATING_DECN_ID = B.RATING_DECN_ID
 AND    (  A.DGNSTC_TYPE_CD ='8045' -- TBI,
         OR A.HYPNTD_DGNSTC_TYPE_CD ='8045');  
COMMIT ;
 

SELECT COUNT(*), COUNT(DISTINCT VA_CLAIM_NUM), 
       COUNT(DISTINCT VA_CLAIM_NUM||RATING_DATE)
FROM   AH4331_RERUN_4;
-- 526    472    472

 
CREATE TABLE AH4331_RERUN_FINAL AS
SELECT DISTINCT 
       A.VETERAN,
       A.VES_NUM,
       A.EXAM_DATE,
       A.VA_CLAIM_NUM,
       A.SSN,
       A.PTCPNT_VET_ID,
       A.RBA_RO,
       A.RATING_DATE,
       A.DSBLTY_ID,
       A.DSBLTY_DECN_TYPE_CD, 
       (SELECT C.NM FROM COMMON_SS.SS_TYPE C
        WHERE A.DSBLTY_DECN_TYPE_CD = C.CD
        AND C.GROUP_TYPE_NM = 'DSBLTY_DECN_TYPE') AS DECISION,
       A.DSBLTY_DECN_BASIS_TYPE_CD,
       (SELECT T.NM FROM COMMON_SS.SS_TYPE T
        WHERE A.DSBLTY_DECN_BASIS_TYPE_CD = T.CD
        AND T.GROUP_TYPE_NM = 'DSBLTY_DECN_BASIS_TYPE') AS DECISION_BASIS,
       A.HYPNTD_DGNSTC_TYPE_CD,
       A.DGNSTC_TYPE_CD,
       A.BEGIN_DT,
       A.PRCNT_NBR,
       A.DGNSTC_TXT

FROM   AH4331_RERUN_4 A
ORDER BY A.VA_CLAIM_NUM, A.DSBLTY_ID, A.BEGIN_DT;
COMMIT;

 
 
SELECT COUNT(*), COUNT(DISTINCT VA_CLAIM_NUM), 
       COUNT(DISTINCT VA_CLAIM_NUM||DSBLTY_ID)
FROM   AH4331_RERUN_FINAL;
-- 525    472    515
                                                               
     
                  
SELECT COUNT(*), COUNT(DISTINCT VA_CLAIM_NUM) FROM AH4331_RERUN_FINAL
WHERE VA_CLAIM_NUM = '316804516'; -- 2 RECORDS

SELECT COUNT(*), COUNT(DISTINCT VA_CLAIM_NUM) FROM AH4331_RERUN_FINAL
WHERE VA_CLAIM_NUM = '453632300'; '316804516'; -- 2 RECORDS



SELECT  * FROM AH4331_RERUN_FINAL ORDER BY VA_CLAIM_NUM, DSBLTY_ID, BEGIN_DT;


