-- ALL TABLES IN DMODCUNN SCHEMA UNLESS OTHERWISE NOTED

/*
1.    Compensation Service is requesting a current listing (to the date of 
       the response to this request) of living Veterans who are service 
       connected for ALS (Amyotrophic Lateral Sclerosis) under the four digit 
       diagnostic code (DC) 8017, by degree of disability of 100% without an 
       entitlement rating for Specially Adaptive Housing (SAH).  
2.    Please include claim jurisdiction.
3.    Please search Corporate, BDN and VETSNET, and BIRLS.

OUTPUT:
1.    Claim number
2.    Names of Veterans
3.    Diagnostic code 8017
4.    Regional Office that each Veteran is associated with and unique counts 
         of Veterans as described above.  
*/


/* 
-- COMPARE VBI RESULTS AND ALL_DIAG_ADHOC RESULTS
CREATE TABLE AH4431_VBI AS
SELECT  C.PERSON_DIM_SID AS VETERAN_PERSON_DIM_SID, P.FILE_NBR, P.BRTHDY_DT,
        D.PTCPNT_VET_ID, P.LAST_NM, P.FIRST_NM, P.MIDDLE_NM
FROM    DW_ADHOC.VBI_DIAGNOSIS D, COMMON_SS.SS_PERSON P, EDW.PERSON_DIM C
WHERE   D.PTCPNT_VET_ID = P.PTCPNT_ID
AND     P.FILE_NBR = C.FILE_NUMBER
AND     D.BENEFIT_MONTH_DIM_SID = (SELECT MAX(BENEFIT_MONTH_DIM_SID) 
                                   FROM   DW_ADHOC.VBI_DIAGNOSIS)
AND     TO_NUMBER(D.DGNSTC_TYPE_CD) = 8017 
AND     D.DSBLTY_DECN_TYPE_CD = 'SVCCONNCTED'
AND     D.PRCNT_NBR = 100
AND     C.CURRENT_RECORD_IND = 'Y'
AND     C.VETERAN_IND = 'Y'
AND     P.DEATH_DT IS NULL;  
COMMIT;


SELECT COUNT(*), COUNT(FILE_NBR) FROM AH4431_VBI;
-- 919    919 
-- SINCE THERE ARE FEWER RESULTS WITH THE VBI CODE THAN WITH THE ALL_DIAG_ADHOC,
-- WILL USE THE ALL_DIAG_ADHOC CODE
DROP TABLE AH4431_VBI PURGE;
COMMIT;
*/

-- re-run 12-17-2013 at Comp Svc request

-- CREATE BASE TABLE OF LATEST RATING FOR ALL VETERANS 100% SC FOR DC 8017
CREATE TABLE AH4431_BASE AS (
(SELECT DISTINCT A.FILE_NBR, P.LAST_NM, P.FIRST_NM, P.MIDDLE_NM
FROM   DW_ADHOC.ALL_DIAG_ADHOC A, COMMON_SS.SS_PERSON P
WHERE  A.FILE_NBR = P.FILE_NBR
AND    A.PTCPNT_VET_ID = P.PTCPNT_ID
AND    P.DEATH_DT IS NULL
AND    A.RATING_DECN_BEGIN_DT <= SYSDATE
AND    A.RATING_DT IS NOT NULL
AND    A.HYPNTD_DGNSTC_TYPE_CD IS NULL
AND    A.DGNSTC_TYPE_CD = '8017'
AND    A.DECN_TYPE_CD = 'SVCCONNCTED' 
AND    A.PRCNT_NBR = 100
AND    A.PRMLGN_DT IS NOT NULL
AND    NVL(A.RATING_DECN_END_DT,(TO_DATE('10/01/2050','MM/DD/YYYY'))) > SYSDATE
AND    NVL(A.DISABILITY_INACTIVE_DT,(TO_DATE('10/01/2050','MM/DD/YYYY'))) > SYSDATE
AND    NVL(A.RATING_INACTIVE_DT,(TO_DATE('10/01/2050','MM/DD/YYYY'))) > SYSDATE
AND    A.PRMLGN_DT =  (SELECT MAX(RBAP.PRMLGN_DT)
                       FROM   DW_ADHOC.ALL_DIAG_ADHOC RBAP
                       WHERE  A.FILE_NBR = RBAP.FILE_NBR
                       AND    A.PTCPNT_VET_ID = RBAP.PTCPNT_VET_ID
                       AND    RBAP.RATING_DT IS NOT NULL
                       AND    RBAP.PRMLGN_DT < SYSDATE))
UNION
(SELECT B.CLAIM_NUMBER AS FILE_NBR, B.LAST_NAME AS LAST_NM, 
        B.FIRST_NAME AS FIRST_NM, B.MIDDLE_NAME AS MIDDLE_NM
 FROM   BIRLS_STG.BIRLS_DIAGNOSIS D, BIRLS_STG.BIRLS_MAIN B
 WHERE  B.CLAIM_NUMBER = D.CLAIM_NUMBER
 AND    B.DATE_OF_DEATH IS NULL
 AND    D.SERVICE_DIAGNOSTICS = '8017'
 AND    D.SERVICE_PERCENT = '100'
 AND    D.RECUR_SVC_CON_DISABILITY = 'Y'));



SELECT COUNT(*), COUNT(FILE_NBR) FROM AH4431_BASE;
-- 825   825 original
-- re-run  885             885

 
-- DELETE ANY RECORDS WITH DATE OF DEATH IN CORPORATE
DELETE FROM AH4431_BASE A WHERE A.FILE_NBR IN
(SELECT P.FILE_NBR
 FROM   COMMON_SS.SS_PERSON P
 WHERE  P.FILE_NBR = A.FILE_NBR
 AND    P.DEATH_DT IS NOT NULL);
COMMIT;


-- DELETE ANY RECORDS WITH DATE OF DEATH IN BIRLS
DELETE FROM AH4431_BASE A WHERE A.FILE_NBR IN
(SELECT B.CLAIM_NUMBER AS FILE_NBR
 FROM   BIRLS_STG.BIRLS_MAIN B
 WHERE  B.CLAIM_NUMBER = A.FILE_NBR
 AND    B.DATE_OF_DEATH IS NOT NULL);
COMMIT;

SELECT COUNT(*), COUNT(FILE_NBR) FROM AH4431_BASE;
-- 825   825 original
-- re-run  885             885

-- DELETE ANY RECORDS WHERE BIRLS SHOWS SAH ENTITLEMENT 
DELETE FROM AH4431_BASE A WHERE A.FILE_NBR IN
(SELECT B.CLAIM_NUMBER AS FILE_NBR
 FROM   BIRLS_STG.BIRLS_MAIN B 
 WHERE  B.CLAIM_NUMBER = A.FILE_NBR
 AND    B.SPECIAL_ADAPTIVE_HOUSING = 'Y');
COMMIT;

SELECT COUNT(*), COUNT(FILE_NBR) FROM AH4431_BASE;
-- 820    820  original
-- re-run  881             881


-- add participant ID to match to ratings
CREATE TABLE AH4431_BASE_2 AS
SELECT A.*, P.PTCPNT_ID
FROM   AH4431_BASE A, COMMON_SS.SS_PERSON P
WHERE  A.FILE_NBR = P.FILE_NBR(+);
COMMIT;

 
-- find ratings for SAH, keep latest if granted
CREATE TABLE AH4431_SAH AS
SELECT DISTINCT PTCPNT_VET_ID, 'Y' SPCL_ADAPTIVE_HSNG_IND
FROM
((SELECT Z.PTCPNT_VET_ID, Z.ANCILY_DECN_TYPE_CD, Z.RATING_DECN_ID, Z.PRFIL_DT
FROM 
(SELECT X.*, ROW_NUMBER() OVER(PARTITION BY X.PTCPNT_VET_ID ORDER BY
  X.RATING_DECN_ID DESC) AS SAH_RANK
FROM 
(SELECT DISTINCT RD.*, AR.ANCILY_DECN_TYPE_CD
 FROM   RBA_SS.SS_ANCILY_RATING AR,
        RBA_SS.SS_RATING_DECN RD, AH4431_BASE_2 A
 WHERE  RD.PTCPNT_VET_ID = A.PTCPNT_ID
 AND    RD.RATING_DECN_ID = AR.RATING_DECN_ID
 AND    AR.ANCILY_DECN_TYPE_CD IN ('ESAH','NESAH')
 AND    RD.PRFIL_DT =  (SELECT MAX(RBAP.PRFIL_DT)
                        FROM   RBA_SS.SS_RBA_PRFIL RBAP
                        WHERE  A.PTCPNT_ID = RBAP.PTCPNT_VET_ID
                        AND    RBAP.PRMLGN_DT IS NOT NULL
                        AND    RBAP.RATING_DT <= sysdate)) X ) Z
WHERE Z.SAH_RANK = 1)
UNION
(SELECT Z.PTCPNT_VET_ID, Z.ANCILY_DECN_TYPE_CD, Z.RATING_DECN_ID, Z.PRFIL_DT
FROM 
(SELECT X.*, ROW_NUMBER() OVER(PARTITION BY X.PTCPNT_VET_ID ORDER BY
  X.RATING_DECN_ID DESC) AS SAH_RANK
FROM 
(SELECT DISTINCT RD.*, AR.ANCILY_DECN_TYPE_CD
 FROM   RBA_SS.SS_ANCILY_RATING AR,
        RBA_SS.SS_RATING_DECN RD, AH4431_BASE_2 A
 WHERE  RD.PTCPNT_VET_ID = A.PTCPNT_ID
 AND    RD.RATING_DECN_ID = AR.RATING_DECN_ID
 AND    AR.ANCILY_DECN_TYPE_CD IN ('ESHA','NESHA')
 AND    RD.PRFIL_DT =  (SELECT MAX(RBAP.PRFIL_DT)
                        FROM   RBA_SS.SS_RBA_PRFIL RBAP
                        WHERE  A.PTCPNT_ID = RBAP.PTCPNT_VET_ID
                        AND    RBAP.PRMLGN_DT IS NOT NULL
                        AND    RBAP.RATING_DT <= sysdate)) X ) Z
WHERE Z.SAH_RANK = 1))  

WHERE ANCILY_DECN_TYPE_CD IN ('ESAH','ESHA');
COMMIT;


-- delete SAH grants from base table  
DELETE FROM AH4431_BASE_2 WHERE PTCPNT_ID IN 
(SELECT DISTINCT PTCPNT_VET_ID FROM AH4431_SAH);
 


SELECT COUNT(*), COUNT(FILE_NBR) FROM AH4431_BASE_2;
-- 739    739 original
-- re-run  792             792


-- ADD STATION NUMBER FOR RUNNING AWARD
CREATE TABLE AH4431_BASE_3 AS
SELECT B.*, '8017' DIAG_CODE, C.AWARD_STN_NBR

FROM   AH4431_BASE_2 B,

      (SELECT /* + parallel (a,5) */
              DISTINCT A.FILE_NBR, A.AWARD_STN_NBR
       FROM   COMMON_SS.SS_AWARD_CMPSIT A,
              AH4431_BASE_2 P
       WHERE  A.FILE_NBR = P.FILE_NBR
       AND    A.PTCPNT_VET_ID = A.PTCPNT_BENE_ID
       AND    A.PTCPNT_BENE_ID = A.APORTN_RECIP_ID
       AND    A.AWARD_CURNT_STATUS_CD = 'A'
       AND    A.PAYEE_TYPE_CD = '00'
       AND    A.ENTLMT_TYPE_CD != '81'
       AND    SUBSTR(A.ENTLMT_TYPE_CD,2,1) IN ('1','2','3','4','L')) C

WHERE B.FILE_NBR = C.FILE_NBR(+);
 


-- ADD COVERS LOCATION SINCE NOT ALL RECORDS HAVE A RUNNING AWARD 
CREATE TABLE AH4431_BASE_4 AS
SELECT A.*, B.COVERS_RO

FROM   AH4431_BASE_3 A,

      (SELECT A.FILE_NBR, C.LCTN_FCLTY_ID AS COVERS_RO
       FROM   AH4431_BASE_3 A, COVERS_SS.SS_CVRS_FOLDER C
       WHERE  A.FILE_NBR = C.FILE_NBR
       AND    C.PAYEE_CD = '00'
       AND    C.VOLUME_CD = '01'
       AND    C.FOLDER_TYPE_CD = 'C') B

WHERE  A.FILE_NBR = B.FILE_NBR(+);
 
 
 
-- ADD BIRLS FOLDER LOCATION SINCE SOME RECORDS HAVE NO RUNNING AWARD
-- AND NO COVERS RECORD
CREATE TABLE AH4431_FINAL AS
SELECT A.*, B.BIRLS_FOLDER_LOCATION

FROM   AH4431_BASE_4 A,

      (SELECT A.FILE_NBR, C.FOLDER_CURRENT_LOCATION AS BIRLS_FOLDER_LOCATION
       FROM   AH4431_BASE_4 A, BIRLS_STG.BIRLS_FOLDER_TYPE C
       WHERE  A.FILE_NBR = C.CLAIM_NUMBER
       AND    C.FOLDER_TYPE = 'CLAIM') B

WHERE  A.FILE_NBR = B.FILE_NBR(+);
 

SELECT COUNT(*), COUNT(FILE_NBR) FROM AH4431_FINAL;
-- 739    739  original
-- re-run  792             792


SELECT * FROM AH4431_FINAL;



 



 